// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtXm4QpEf4tV9u67HXAK1K5bD8T_UeO8',
    appId: '1:130023134061:web:51728aaa4a79bddd040064',
    messagingSenderId: '130023134061',
    projectId: 'scfacademy-51693',
    authDomain: 'scfacademy-51693.firebaseapp.com',
    storageBucket: 'scfacademy-51693.appspot.com',
    measurementId: 'G-9ZRVX6GYG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHODWkhp1-ygK9HHQXLldYiZwq5ccKrk',
    appId: '1:130023134061:android:c4d38e9459e9e9b1040064',
    messagingSenderId: '130023134061',
    projectId: 'scfacademy-51693',
    storageBucket: 'scfacademy-51693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjldw38qd4K1zgCpZOChEnKlPr0Po06Zk',
    appId: '1:130023134061:ios:00624afcd89aea4b040064',
    messagingSenderId: '130023134061',
    projectId: 'scfacademy-51693',
    storageBucket: 'scfacademy-51693.appspot.com',
    iosBundleId: 'com.example.eduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjldw38qd4K1zgCpZOChEnKlPr0Po06Zk',
    appId: '1:130023134061:ios:00624afcd89aea4b040064',
    messagingSenderId: '130023134061',
    projectId: 'scfacademy-51693',
    storageBucket: 'scfacademy-51693.appspot.com',
    iosBundleId: 'com.example.eduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEtXm4QpEf4tV9u67HXAK1K5bD8T_UeO8',
    appId: '1:130023134061:web:cac20c59c02d7158040064',
    messagingSenderId: '130023134061',
    projectId: 'scfacademy-51693',
    authDomain: 'scfacademy-51693.firebaseapp.com',
    storageBucket: 'scfacademy-51693.appspot.com',
    measurementId: 'G-RQZD51CLGM',
  );
}
